#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 (小火箭) | 快捷指令:设置位置 https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 清理恢复 https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f | 选点:https://changeapplelocation.appleai.workers.dev/ | 使用方法:选点 -> 储存 -> 开关定位服务或重启生效
#!author=AgentOpenAI
#!homepage=https://github.com/AgentOpenAI/ChangeAppleLocation
#!icon=https://raw.githubusercontent.com/AgentOpenAI/ChangeAppleLocation/refs/heads/master/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/AgentOpenAI/ChangeAppleLocation/refs/heads/master/dist/wloc.js,argument=longitude=0&latitude=0&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/AgentOpenAI/ChangeAppleLocation/refs/heads/master/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
