#!name=Apple WLOC 定位修改
#!desc=修改 Apple 网络定位返回坐标 | 快捷指令:设置位置 https://www.icloud.com/shortcuts/a82717d8fdad4e6280866fcf911173f7 清理恢复 https://www.icloud.com/shortcuts/f42632d406504f24a2cd163af4fe012f | 选点:https://changeapplelocation.appleai.workers.dev/ | 使用方法:选点 -> 储存 -> 开关定位服务或重启生效
#!author=AgentOpenAI
#!homepage=https://github.com/AgentOpenAI/ChangeAppleLocation

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/AgentOpenAI/ChangeAppleLocation/refs/heads/master/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/AgentOpenAI/ChangeAppleLocation/refs/heads/master/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
